apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myapp-prod
  namespace: argocd
spec:
  description: myapp (prod)
  sourceRepos:
    - git@github.com:vigneshvinfra/kite.git
  destinations:
    - name: prod
      namespace: myapp-prod
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  syncWindows:
    - kind: deny
      schedule: '* * * * *'
      duration: 24h
      applications: ['*']
      manualSync: true
