apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: secrets-store-csi-prod
  namespace: argocd
spec:
  description: Secrets Store CSI Driver + AWS provider (prod)
  sourceRepos:
    - git@github.com:vigneshvinfra/kite.git
    - https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    - https://aws.github.io/secrets-store-csi-driver-provider-aws
  destinations:
    - name: prod
      namespace: kube-system
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: storage.k8s.io
      kind: CSIDriver
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
