apiVersion: v2
name: secrets-store-csi-driver
type: application
version: 0.1.0
dependencies:
  - name: secrets-store-csi-driver
    version: 1.4.5
    repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  - name: secrets-store-csi-driver-provider-aws
    version: 3.1.0
    repository: https://aws.github.io/secrets-store-csi-driver-provider-aws
