
image:
  tag: dc1a177

env:
  ENV: dev

commonLabels:
  environment: dev
  
resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

# Skip the Ingress in dev

ingress:
  enabled: false