apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
type: Opaque
stringData:
  admin-user: {{ required "grafanaAdmin.user is required" .Values.grafanaAdmin.user | quote }}
  admin-password: {{ required "grafanaAdmin.password is required" .Values.grafanaAdmin.password | quote }}
