apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationsets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: bootstrap
  source:
    repoURL: git@github.com:vigneshvinfra/kite.git
    targetRevision: main
    path: argocd/applicationsets
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
