apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values: [dev, prod]
  template:
    metadata:
      name: 'myapp-{{name}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: 'myapp-{{name}}'
      source:
        repoURL: git@github.com:vigneshvinfra/kite.git
        targetRevision: main
        path: helm/myapp
        helm:
          releaseName: myapp
          valueFiles:
            - values.yaml
            - 'values-{{name}}.yaml'
      destination:
        name: '{{name}}'
        namespace: 'myapp-{{name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
