apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets-store-csi-driver
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values: [prod]
  template:
    metadata:
      name: 'secrets-store-csi-driver-{{name}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: 'secrets-store-csi-{{name}}'
      source:
        repoURL: git@github.com:vigneshvinfra/kite.git
        targetRevision: main
        path: helm/secrets-store-csi-driver
        helm:
          releaseName: secrets-store-csi-driver
          valueFiles:
            - values.yaml
            - 'values-{{name}}.yaml'
      destination:
        name: '{{name}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
