apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myapp-dev
  namespace: argocd
spec:
  description: myapp (dev)
  sourceRepos:
    - git@github.com:vigneshvinfra/kite.git
  destinations:
    - name: dev
      namespace: myapp-dev
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
